name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment variable for timestamp
      id: vars
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file src/app/Dockerfile --tag luneforge:${{ env.TIMESTAMP }}

    - name: Push the Docker image to Docker Hub
      run: |
        docker tag luneforge:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_USER }}/luneforge:latest
        docker push ${{ secrets.DOCKER_USER }}/luneforge:latest
